AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Trello Power-Up deployed on AWS Amplify'

Parameters:
  RepositoryUrl:
    Type: String
    Description: GitHub repository URL (e.g., https://github.com/username/repo)

  GitHubToken:
    Type: String
    Description: GitHub personal access token for repository access
    NoEcho: true

  BranchName:
    Type: String
    Default: main
    Description: Git branch to deploy

  AppName:
    Type: String
    Default: trello-powerup-hello-world
    Description: Name of the Amplify application

Resources:
  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify
      Path: /service-role/

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Repository: !Ref RepositoryUrl
      AccessToken: !Ref GitHubToken
      IAMServiceRole: !GetAtt AmplifyServiceRole.Arn
      BuildSpec: |
        version: 1
        frontend:
          phases:
            build:
              commands:
                - echo "Building Trello Power-Up"
          artifacts:
            baseDirectory: /
            files:
              - '**/*'
          cache:
            paths: []
      CustomRules:
        - Source: /<*>
          Target: /index.html
          Status: '404'
      EnvironmentVariables:
        - Name: _LIVE_UPDATES
          Value: '[{"name":"Amplify CLI","pkg":"@aws-amplify/cli","type":"npm","version":"latest"}]'

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref BranchName
      EnableAutoBuild: true
      EnablePullRequestPreview: false
      Framework: Web

Outputs:
  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AppId'

  AmplifyAppUrl:
    Description: Amplify App URL
    Value: !Sub 'https://${BranchName}.${AmplifyApp.DefaultDomain}'
    Export:
      Name: !Sub '${AWS::StackName}-AppUrl'

  AmplifyConsoleUrl:
    Description: Amplify Console URL
    Value: !Sub 'https://console.aws.amazon.com/amplify/home?region=${AWS::Region}#/${AmplifyApp.AppId}'
